// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbKyTbNzDXkbd8EE2rSFDB-ENb70PnC-s',
    appId: '1:494131482092:web:3d09992e810f762761c4c9',
    messagingSenderId: '494131482092',
    projectId: 'flutter-belajar-web',
    authDomain: 'flutter-belajar-web.firebaseapp.com',
    storageBucket: 'flutter-belajar-web.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9GQTVVh54IKFhd8ujjL64x1BSdevpebY',
    appId: '1:494131482092:android:bb43af20acc12a8161c4c9',
    messagingSenderId: '494131482092',
    projectId: 'flutter-belajar-web',
    storageBucket: 'flutter-belajar-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsvwUUeh2mrc2bX812OUXl_18EVtgjuK4',
    appId: '1:494131482092:ios:70818e2dc349299561c4c9',
    messagingSenderId: '494131482092',
    projectId: 'flutter-belajar-web',
    storageBucket: 'flutter-belajar-web.appspot.com',
    androidClientId: '494131482092-ar7c1gv7q6qi1g1j6mti6modrhom9eoi.apps.googleusercontent.com',
    iosClientId: '494131482092-l30lps7gkkoo8b11npqvhsss8gqi6sar.apps.googleusercontent.com',
    iosBundleId: 'com.example.webFlutterCoba',
  );
}
